### PR TITLE
added timeout to ReadPipe

### PR DESCRIPTION
**Pull request by ZecosMAX**

### CODE REVIEW

**Comment by ZecosMAX** [comment]
After debugging problem with occasional program hang every now and then and also troubles with detecting reboot i checked and found out that ReadPipe was stalling without reset, so i added timeout of 1sec and every problem (at least) that i've encountered has gone away and i was able to unlock bootloader

**Comment by gus33000** [comment]
Thanks. I can see how there could be an issue here however I do have some concerns with the patch here:

The pipe policy should not be reset after a read or write op, here it is set everytime a read is called. This does not look ideal to me.

It is possible some transfers are done that would require more than a second to be performed, leading to potential corruptions depending on the payload size here.

The original value isnt retrieved either and I am not too sure if the default is infinite.

I think it would be better suited to call the policy api here outside of that class where it is more needed. (In the consumers of read pipe for example or at another location)

Issue may also occur with writing not just reading.

**Comment by ZecosMAX** [comment]
it's a crude and quick fix i understand, to be more in-place solution it should be set when timeout is crucial for data receiving and then set back to 0, maybe later when i'll have more time to look into code i'll implement that.

Interesting that for Qualcomm routines there is timeout set before read calls, but not for lumia

**Review by gus33000 — CHANGES_REQUESTED** [review]
See comments in pr

**Comment by gus33000** [comment]
As I expected originally as well, a default timeout is also already set to 5 seconds: https://github.com/ReneLergner/WPinternals/blob/83c09bdc81c798db5e98bb813284d3b0b928fa62/WPinternals/WinUSBNet/USBDevice.cs#L234

My key issues here remain, the timeout should not be set like this in the read function, that's really not ideal and is going to lead to further problems that are going to be hard to debug. Plus the policy set call here would set it for all operations not just reading.

A public api already exists for this and should be used instead outside of the class.

Above link also references the intended way to set such policy, I would prefer seeing this being used to avoid further border issues here.

We also need to understand if the issue we're trying to fix here really is linked to a missing timeout and not something else. It could be just an async problem at play.

**Comment by xplanthris** [comment]
Ok so while I do understand the risks, I can vouch for this PR as it does fix my problem.

**Comment by gus33000** [comment]
This PR will automatically be closed and will not be merged in a week due to inactivity and no consensus on fixes.

**Pull request closed without merging**
